#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
string="rewrite ^/redirect_me https://www.youtube.com/ permanent;"
sudo sed -i "66i $string" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
error="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "44i $error" /etc/nginx/sites-available/default
sudo service nginx restart