#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*
sudo sed -i '$a frontend Accesos_HTTP' /etc/haproxy/haproxy.cfg
sudo sed -i '$a \\tbind    *:80' /etc/haproxy/haproxy.cfg
sudo sed -i '$a \\tmode    http' /etc/haproxy/haproxy.cfg
sudo sed -i '$a \\toption  httpclose' /etc/haproxy/haproxy.cfg
sudo sed -i '$a \\toption  http-server-close' /etc/haproxy/haproxy.cfg
sudo sed -i '$a \\toption  forwardfor' /etc/haproxy/haproxy.cfg
sudo sed -i '$a \\tdefault_backend web-backend \n' /etc/haproxy/haproxy.cfg
sudo sed -i '$a backend web-backend' /etc/haproxy/haproxy.cfg
sudo sed -i '$a \\tmode    http' /etc/haproxy/haproxy.cfg
sudo sed -i '$a \\tbalance roundrobin' /etc/haproxy/haproxy.cfg
sudo sed -i '$a \\tserver 942-web-01 35.231.14.143:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i '$a \\tserver 942-web-02 35.229.85.187:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
