#!/usr/bin/env bash
#Bash script that:
echo "$$" > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' 15
trap 'rm /var/run/holbertonscript.pid; exit' 3
trap 'echo Y U no love me?!' 2
for ((;;))
    do
	echo "To infinity and beyond"
	sleep 2
    done
