#!/usr/bin/env bash
# This script prints Holberton School 10 times using while loop
p='Holberton School'
i=1
while [ $i -le 10 ]
do
    if [ $i == 9 ]
    then
	echo "Hi"
    else
	echo "$p"
    fi
    let i++
done
