#!/usr/bin/env bash
# This script prints Holberton School 10 times using while loop
p='Holberton School'
i=1
while [ $i -le 10 ]
do
    if [ $i == 4 ]
    then
	echo "bad luck"
    elif [ $i == 8 ]
    then
	echo "good luck"
    else
	echo "$p"
    fi
    let i++
done
