#!/usr/bin/env bash
# This script prints numbers between 1 and 20  using while loop
#and says wich are bad luck numbers
i=1
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    let i++
done
