#!/usr/bin/env bash
# This script prints Holberton School 10 times using while loop
i=0
j=1
while [ $i -le 12 ]
do
    echo "Hour: $i"
    while [ $j -le 59 ]
    do
	echo "$j"
	let j++
    done
    let j=1
    let i++
done
