#!/usr/bin/env bash
# Bash script that accepts one argument
# the script should run the whoami command under the user passed as an argument
# make sure to try your script by passing different users
sudo -u "$1" -H sh -c "whoami; exit"