#!/usr/bin/env bash
#Bash script that configures the container to fit the above requirements
sudo pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart